use serde::Serialize;

#[derive(Clone, Debug, Serialize)]
pub struct RunReport {
    pub version: u32,
    pub input: InputReport,
    pub ontology: OntologyReport,
    pub compiled: CompiledSchemaReport,
    pub rules: RulesReport,
    pub reasoning: ReasoningReport,
    pub peak_rss_bytes: Option<u64>,
    pub wall_time_ms: u128,
    pub ingest_time_ms: u128,
    pub export_time_ms: u128,
}

#[derive(Clone, Debug, Serialize)]
pub struct InputReport {
    pub triples: usize,
    pub dictionary_terms: usize,
    pub output_triples: usize,
    pub memory_budget_bytes: u64,
}

/// Per-category axiom counts from the parsed ontology (before compilation).
#[derive(Clone, Debug, Default, Serialize)]
pub struct OntologyReport {
    pub total_axioms: usize,
    pub subclass_of: usize,
    pub sub_property_of: usize,
    pub domain: usize,
    pub range: usize,
    pub inverse_of: usize,
    pub symmetric_property: usize,
    pub transitive_property: usize,
    pub functional_property: usize,
    pub inverse_functional_property: usize,
    pub property_chain: usize,
    pub has_value: usize,
    pub some_values_from: usize,
    pub all_values_from: usize,
    pub intersection_of: usize,
    pub complement_of: usize,
    pub one_of: usize,
    pub max_cardinality_zero: usize,
    pub max_cardinality_one: usize,
    pub disjoint_classes: usize,
    pub disjoint_properties: usize,
    pub irreflexive_property: usize,
    pub asymmetric_property: usize,
    pub has_key: usize,
    pub same_individual: usize,
    pub different_individuals: usize,
    pub negative_property_assertion: usize,
    pub swrl_rules: usize,
}

/// Stats from the compiled schema (after closure computation and normalization).
#[derive(Clone, Debug, Default, Serialize)]
pub struct CompiledSchemaReport {
    pub subclass_closure_size: usize,
    pub subproperty_closure_size: usize,
    pub domain_entries: usize,
    pub range_entries: usize,
    pub inverse_entries: usize,
    pub property_chains: usize,
    pub chain_trigger_entries: usize,
    pub universal_types: usize,
    pub has_value_rules: usize,
    pub some_values_from_rules: usize,
    pub all_values_from_rules: usize,
    pub intersection_rules: usize,
    pub max_cardinality_one_rules: usize,
    pub swrl_rules_compiled: usize,
    pub indexed_predicates: usize,
    pub indexed_classes: usize,
    pub proxy_terms: usize,
    pub schema_closure_iterations: usize,
    pub schema_closure_inferred: usize,
}

#[derive(Clone, Debug, Serialize)]
pub struct RulesReport {
    pub active: Vec<String>,
    pub unsupported_encountered: Vec<String>,
}

#[derive(Clone, Debug, Serialize)]
pub struct ReasoningReport {
    pub strata: Vec<StratumReport>,
    pub iterations: Vec<IterationReport>,
    pub total_inferred: usize,
    pub total_iterations: usize,
    pub fixpoint_reached: bool,
    pub equality_merges: usize,
    pub equality_iterations: usize,
    pub rule_firings: RuleFirings,
    pub inconsistencies: Vec<InconsistencyReport>,
}

/// Per-iteration breakdown of new facts discovered.
#[derive(Clone, Debug, Default, Serialize)]
pub struct IterationReport {
    pub iteration: usize,
    pub new_types: usize,
    pub new_properties: usize,
}

/// Counts of candidate facts generated by each rule category.
#[derive(Clone, Debug, Default, Serialize)]
pub struct RuleFirings {
    pub subclass: usize,
    pub subproperty: usize,
    pub domain: usize,
    pub range: usize,
    pub inverse: usize,
    pub symmetric: usize,
    pub transitive: usize,
    pub has_value: usize,
    pub some_values_from: usize,
    pub all_values_from: usize,
    pub intersection: usize,
    pub universal_type: usize,
    pub property_chain: usize,
    pub swrl: usize,
}

#[derive(Clone, Debug, Serialize)]
pub struct InconsistencyReport {
    pub kind: String,
    pub detail: String,
}

#[derive(Clone, Debug, Serialize)]
pub struct StratumReport {
    pub name: String,
    pub iterations: usize,
    pub inferred: usize,
    pub time_ms: u128,
}
